.TH ALSAUNMUTE 1 2012-11-19
.SH NAME
alsaunmute \- a simple script to initialize ALSA sound devices

.SH SYNOPSIS
.BR alsaunmute

.SH DESCRIPTION
.B alsaunmute
is a shell script which runs the
.BR alsactl (1)
utility with
.I init
argument (see the script for details).

.SH OPTIONS
None.

.SH AUTHORS
.B alsaunmute
is written by Jaroslav Kysela <perex@perex.cz>.

.SH SEE ALSO
.BR alsactl (1),
.BR alsamixer (1),
.BR amixer (1)
